---
- name: Install CollectD on RedHat OS family
  yum: name={{ item.package }} 
       state=latest
  with_items: collectd_packages_{{ ansible_os_family }}
  tags:
   - collectd_install

- name: Copy main CollectD Configuration on RedHat OS family
  template: src=collectd.conf.j2
            dest={{ collectd_conf_rh }}
            backup=yes
            owner=root
            group=root
            mode=0644
  notify:
   - restart collectd
  tags:
   - collectd_configure
